FROM python:3.10-slim

WORKDIR /app

COPY backend/ ./backend
COPY contracts/ ./contracts

RUN apt-get update && apt-get install -y bash

RUN pip install --upgrade pip && pip install -e ./backend

ENTRYPOINT ["python", "-m", "backend.cli"]
