[profile.default]
src = "src"
out = "out"
libs = ["lib"]
chain_id = 84532
evm_version = "paris"

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
